\chapter{Обработка исключений изнутри: Условия и Перезапуск}
\label{ch:19}

Одной из замечательных особенностей Лиспа является его система \textit{условий}. Она
служит тем же целям, что и системы обработки исключений в Java, Python и C++, но является
более гибкой. На самом деле её способности выходят за пределы обработки ошибок~--- условия
являются более всеохватывающими, чем исключения, в том смысле, что условия могут
представить любое событие во время выполнения программы, которое может представлять
интерес в программировании различных уровней стека вызовов. Например в секции "Другие
применения условий" вы увидите, что условия могут быть использованы для выдачи
предупреждения без нарушения выполнения кода, который выдаёт предупреждение, в то же время
позволяя коду выше на стеке вызовов контролировать, напечатано ли предупреждающее
сообщение. Пока, однако, я сосредоточусь на обработке ошибок.

Система условий более гибка, чем система исключений, потому что вместо разделения на две
части между кодом, который сигнализирует об ошибке\footnote{выбрасывает (throw) или
  вызывает (raise) исключение в терминах Java/Python.} и кодом, который обрабатывает
её\footnote{ловит (catch) исключение в терминах Java/Python}, система условий разделяет
ответственность на три части~--- \textit{сигнализация} условия, его \textit{обработка} и
\textit{перезапуск}. В этой главе я опишу, как можно использовать условия в гипотетическом
приложении для анализа журнальных файлов. Вы увидите, как можно использовать систему
условий, чтобы дать возможность низкоуровневой функции обнаружить проблему в процессе
разбора журнального файла и сигнализировать об ошибке, коду на промежуточном уровне
предоставить несколько возможных путей исправления такой ошибки и коду на высшем уровне
приложения определить политику для выбора стратегии исправления.

Для начала я введу некоторую терминологию: \textit{ошибки}, как я буду использовать этот
термин, есть последствие закона Мёрфи. Если может случиться что-то плохое, оно случится:
файл, который ваша программа должна прочесть, будет потерян, диск, на который вам надо
записать, будет полон, сервер, с которым вы общаетесь, упадёт или исчезнет сеть. Если
что-то из этих вещей случилось, это может помешать участку кода выполнить то, что вы
хотите. Но это не программная ошибка: нет места в коде, которое вы можете исправить, чтобы
сделать несуществующий файл существующим или освободить место на диске. Однако если
оставшаяся часть программы зависит от действий, которые должны были быть сделаны, то вам
лучше как-то разобраться с происшествием, иначе вы ошибку \textit{закладываете}. Итак,
ошибки не всегда бывают программными, но их игнорирование~--- это всегда ошибка в
программе.

Что же означает обработать ошибку? В хорошо написанной программе каждая функция~--- это
чёрный ящик, скрывающий внутреннее содержание своей работы. Программы таким образом
строятся из функций разных уровней: функции на высшем уровне построены на функциях более
низкого уровня и так далее. Эта иерархия функционирования выражается во время выполнения в
форме стека вызовов: когда \code{высший} вызывает \code{среднеднего}, а он в свою очередь
вызывает \code{нижнего}, то поток выполнения находится внизу, но он также проходит через
\code{средний} и \code{высший} уровни, поэтому они все находятся в одном стеке вызовов.

Так как каждая функция является чёрным ящиком, связи между функциями~--- прекрасное место
для работы с ошибками. Каждая функция~--- \code{нижняя} для примера~--- должна делать
какую-то работу. Та, которая её непосредственно вызывает~--- \code{средняя} в нашем случае
~--- рассчитывает на неё в своей работе. Однако ошибка, которая мешает ей сделать свою
работу, подвергает всех вызывающих риску: \code{средняя} вызывала \code{нижнюю}, потому
что ей нужна работа, которую \code{нижняя} делает; если эта работа не сделана, у
\code{средней} проблемы. Но это означает, что у вызвавшей \code{среднюю}, \code{высшей},
тоже проблемы~--- и так далее вверх по стеку вызовов вплоть до верха программы. С другой
стороны, так как каждая функция чёрный ящик, если какая-то функция в стеке вызовов может
как-то сделать свою работу не смотря на проблемы у тех, кто пониже, то никакой функции
повыше не надо знать, что проблемы вообще были~--- все эти функции заботятся только чтобы
функции, которые они вызывают, как-то сделали работу, которую от них ждут.

В большинстве языков ошибки обрабатываются путём возврата из упавшей функции и передачи
шанса вызывающей функции или всё исправить или упасть самой. Некоторые языки используют
обычный механизм возврата из функций, в то время как языки с исключениями возвращают
контроль через \textit{выброс} или \textit{возбуждение} исключения. Исключения~--- это
огромное усовершенствование над использованием обычных возвратов функций, но обе схемы
страдают от общего порока: пока ищется функция, которая может восстановиться, стек
пустеет. Это приводит к тому, что код, который может всё восстановить, должен сделать это
без контекста того, что код нижнего уровня пытался сделать, когда случилась ошибка.

Рассмотрим гипотетическую цепочку вызовов из \code{высшей}, \code{средней}, \code{нижней}
функций. Если \code{нижняя} падает, и \code{средняя} не может всё поправить, дело
передаётся в суд высшей инстанции. Для \code{высшей}, чтобы обработать ошибку, надо или
сделать свою работу без помощи \code{средней}, или как-то всё изменить, чтобы вызов
\code{средней} работал, и вызвать её снова. Первый вариант теоретически прост, но
предполагает кучу лишнего кода~--- полное воплощение того, что, предполагалось, сделает
\code{средняя}. И чем дальше стек освобождается, тем больше работы, которую следует
переделать. Второй вариант~--- исправление ситуации, и ещё одна попытка~--- запутанный:
для \code{высшей}, чтобы иметь возможность изменить ситуацию в мире так, чтобы второй
вызов \code{средней} не закончился ошибкой в \code{нижней}, необходимо неподобающее ей
знание внутреннего устройства обеих функций: \code{средней} и \code{нижней}, что
противоречит идее, что каждая функция является чёрным ящиком.

\section{Путь языка Лисп}

Система обработки ошибок в языке Common Lisp даёт вам выход из этого тупика, позволяя вам
отделить код, который исправляет ошибки, от кода, который решает, как их исправлять. Таким
образом, вы можете поместить код восстановления в функции низкого уровня, на самом деле не
обязывая использовать какуй-то конкретную стратегию восстановления, предоставляя решать
это коду функций высшего уровня.

Чтобы почувствовать, как это работает, предположим, что вы пишете приложение, которое
читает какой-то текстовый файл наподобие журнала Web-сервера. Где-то в вашем приложении
будет ваша функция разбора отдельных журнальных записей. Давайте предположим, что вы
напишете функцию \code{parse-log-entry}, которой будет передаваться строка, содержащая
одну журнальную запись, и которая предположительно вернёт объект \code{log-entry},
представляющий эту запись. Эта функция будет вызываться из функции \code{parse-log-file},
которая читает журнальный файл полностью и возвращает список объектов, представляющий все
записи в журнале.

Чтобы всё упростить, от функции \code{parse-log-entry} не будет требоваться разбирать
неправильно сформированные записи. Однако она будет способна распознать, когда её ввод
неправилен. Но что она должна делать, когда она определяет неправильный ввод? В языке C вы
бы вернули специальное значение, чтобы обозначить, что была проблема. В языках Java или
Python вы бы выбросили или возбудили исключение. В Common Lisp вы сигнализируете условие.

\section{Условия}

\textit{Условие}~--- это объект, чей класс обозначает общую природу условия, а данные
экземпляров класса несут информацию о деталях конкретных обстоятельств, которые приводят к
сигнализации об условии.\footnote{В этом аспекте условия очень похожи на исключения в Java
  или Python, разве что не все условия представляют ошибку или исключительную ситуацию.} В
нашей гипотетической программе анализа журнальных файлов вы можете определить класс
условия \code{malformed-log-entry-error}, с помощью которого \code{parse-log-entry} будет
сигнализировать, если предоставленные ему данные он не сможет разобрать.

Классы условий определяются макросом \code{DEFINE-CONDITION}, который работает точно так
же, как \code{DEFCLASS}, исключая то, что суперклассом по умолчанию для классов,
определённых с \code{DEFINE-CONDITION}, является \code{CONDITION}, а не
\code{STANDARD-OBJECT}. Слоты определяются так же, и классы условий могут иметь
единственное или множественное наследование от других классов, которые происходят от
\code{CONDITION}. Однако, по историческим причинам от классов условий не требуется быть
экземплярами \code{STANDARD-OBJECT}, так что некоторые из функций, которые вы используете,
и классы которых созданы через \code{DEFCLASS}, не обязательно должны работать с
условиями. В частности, слоты условий недоступны для \code{SLOT-VALUE}: вы должны задать
или опцию \code{:reader}, или опцию \code{:accessor} для любого слота, чьё значение вы
собираетесь использовать. Точно так же новые объекты для условий создаются путём вызова
\code{MAKE-CONDITION}, а не \code{MAKE-INSTANCE}. \code{MAKE-CONDITION} инициализирует
слоты нового условия, основываясь на полученных \code{:initarg}, но способа последующей
настройки инициализации условия, аналогичного \code{INITIALIZE-INSTANCE}, не
существует.\footnote{В некоторых реализациях языка Common Lisp условия определены как
  подкласс от \code{STANDARD-OBJECT}, в этом случае \code{SLOT-VALUE},
  \code{MAKE-INSTANCE}, и \code{INITIALIZE-INSTANCE} будут работать, но на это нельзя
  полагаться из-за непереносимости.}

При использовании системы условий для обработки ошибок вы должны определять ваши условия
как подклассы \code{ERROR}, который является в свою очередь подклассом
\code{CONDITION}. Таким образом, вы можете определить условие
\code{malformed-log-entry-error} со слотом для хранения аргумента, который был передан в
\code{parse-log-entry}, вот так:

\begin{lstlisting}
(define-condition malformed-log-entry-error (error)
  ((text :initarg :text :reader text)))
\end{lstlisting}

\section{Обработчики условий}

В \code{parse-log-entry} вы будете сигнализировать \code{malformed-log-entry-error}, если
вы не сможете разобрать журнальную запись. Вы сигнализируете об ошибках функцией
\code{ERROR}, которая вызывает низкоуровневую функцию \code{SIGNAL} и попадает в отладчик,
если условие не обрабатывается. Можно вызвать \code{ERROR} двумя путями: послать ей уже
сформированный объект условия или послать ей имя класса условия и любые аргументы
инициализации, необходимые для построения нового условия, и она создаст его для вас.
Первое иногда полезно для повторной сигнализации уже существующего объекта условия, а
второе более лаконично. Итак, вы можете записать \code{parse-log-entry} в таком виде,
опуская детали собственно разбора журнальной записи:

\begin{lstlisting}
(defun parse-log-entry (text)
  (if (well-formed-log-entry-p text)
    (make-instance 'log-entry ...)
    (error 'malformed-log-entry-error :text text)))
\end{lstlisting}

То, что происходит, когда сигнализируется ошибка, зависит от кода в стеке вызовов,
стоящего выше \code{parse-log-entry}. Чтобы избежать попадания в отладчик, вы должны
установить \textit{обработчик условия} в одну из функций, предшествующих вызову
\code{parse-log-entry}. Когда условие сигнализируется, механизм сигнализирования
просматривает список активных обработчиков условий, ищя по классу условия обработчик,
способный обработать сигнализируемое условие. Каждый обработчик условия состоит из
спецификатора типа, обозначающего, какие типы условий он может обработать, и функции,
которая получает единственный аргумент~--- условие. В каждый момент времени может быть
несколько активных обработчиков этого условия на различных уровнях стека вызовов. Когда
условие сигнализируется, механизм сигнализирования находит последний установленный
обработчик, чей спецификатор типа совместим с сигнализируемым условием и вызывает его
функцию, передавая ей объект условия.

Функция обработки может выбрать, обрабатывать ли ей условие. Функция может отказаться
обрабатывать условие, просто нормально завершившись, в этом случае управление возвращается
функции \code{SIGNAL}, которая будет искать следующий установленный обработчик с
подходящим спецификатором типа. Для обработки условия функция обязана передать управление
минуя функцию \code{SIGNAL} посредством \textit{нелокального выхода}. В следующей секции
вы увидите, как обработчик может выбрать, куда передать контроль. Однако многие
обработчики условий просто хотят опустошить стек до того места, где они были установлены,
и затем запустить некоторый код. Макрос \code{HANDLER-CASE} как раз устанавливает такой
тип обработчика. Базовая форма \code{HANDLER-CASE} такова:

\begin{lstlisting}
(handler-case expression
  error-clause*)
\end{lstlisting}

где каждая конструкция \textit{error-clause} представляет собой следующую форму:

\begin{lstlisting}
(condition-type ([var]) code)
\end{lstlisting}

Если выражение \textit{expression} завершается нормально, тогда его значение возвращается
из конструкции \code{HANDLER-CASE}. Тело \code{HANDLER-CASE} должно быть одним выражением,
но вы можете использовать \code{PROGN} для объединения нескольких выражений в одну
форму. Если всё же выражение сигнализирует условие, которое является одним из типов
\textit{condition-type}, указанных в одной из секций \textit{error-clause}, то код из
соответствующей секции будет выполнен, и его значение будет возвращено из
\code{HANDLER-CASE}. Если указана переменная \textit{var}, она будет именем переменной,
содержащей объект условия при выполнении кода обработчика. Если код не нуждается в доступе
к объекту условия, вы можете опустить имя переменной.

Например, одним из способов обработки условия \code{malformed-log-entry-error},
сигнализируемого из функции \code{parse-log-entry} в вызывающую её функцию
\code{parse-log-file}, был бы пропуск неправильной записи. В следующей функции выражение
\code{HANDLER-CASE} вернёт либо имя, возвращаемое \code{parse-log-entry}, либо \code{NIL},
если \code{malformed-log-entry-error} сигнализируется. Слово \code{it} во фразе
\code{collect it} цикла \code{LOOP} является ещё одним ключевым словом \code{LOOP},
которое ссылается на значение последнего выполненного условия, в данном случае~--- на
переменную \code{entry}).

\begin{lstlisting}
(defun parse-log-file (file)
  (with-open-file (in file :direction :input)
    (loop for text = (read-line in nil nil) while text
       for entry = (handler-case (parse-log-entry text)
                     (malformed-log-entry-error () nil))
       when entry collect it)))
\end{lstlisting}

Когда функция \code{parse-log-entry} завершается нормально, её значение присваивается
переменной \code{entry} и затем накапливается циклом \code{LOOP}. Но если функция
\code{parse-log-entry} сигнализирует ошибку \code{malformed-log-entry-error}, то
обработчик ошибки вернёт \code{NIL}, который не будет сохранён.

%% START OF TABLE
 Обработка исключений в стиле языка Java 

\code{HANDLER-CASE} в языке Common Lisp является ближайшим аналогом стиля обработки
исключений в языках Java и Python. То, что вы можете записать на языке Java как 

\begin{lstlisting}[language=Java]
try {
  doStuff();
  doMoreStuff();
} catch (SomeException se) {
  recover(se);
}
\end{lstlisting} 

или на языке Python как 

\begin{lstlisting}[language=Python]
try:
  doStuff()
  doMoreStuff()
except SomeException, se:
  recover(se)
\end{lstlisting} 

в языке Common Lisp вы пишите так: 

\begin{lstlisting}
(handler-case
    (progn
      (do-stuff)
      (do-more-stuff))
  (some-exception (se) (recover se)))
\end{lstlisting} 

%% END OF TABLE

Эта версия \code{parse-log-file} имеет один серьёзный недостаток: она делает слишком много
всего. Как предполагает её имя, работа \code{parse-log-file} заключается в разборе файла и
выдаче списка объектов \code{log-entry}; если это невозможно, не её дело решать что
сделать взамен. Что если вы захотите использовать \code{parse-log-file} в приложении,
которое захочет сказать пользователю, что журнальный файл повреждён или в таком, которое
захочет восстановить неправильную запись путём исправления её и разбора снова? Или
приложению достаточно пропускать их до тех пор, пока не накопится определённое количество
повреждённых записей.

Вы можете попытаться решить проблему, переместив \code{HANDLER-CASE} в функцию высшего
уровня. Однако тогда у вас не будет способа воплотить текущую политику пропуска отдельных
записей~--- когда ошибка будет просигнализированна, стек будет опустошён вплоть до функции
высшего уровня, разбор журнального файла будет вообще покинут. Что вам надо, так это
способ предоставить текущую стратегию восстановления без требования всегда её
использовать.

\section{Перезапуск}

Система условий позволяет вам это делать через разделение кода обработки ошибок на две
части. Вы помещаете код, который собственно исправляет ошибки, в перезапуски (restarts), и
обработчик условия может затем обработать условие, запустив подходящий вариант. Код
перезапуска можно положить в средне- или низко-уровневую функцию, такую
\code{parse-log-file} или \code{parse-log-entry}, переместив обработчик условия на высший
уровень в приложении.

Для изменения \code{parse-log-file}, чтобы она устанавливала перезапуск вместо обработчика
условия, вы можете сменить \code{HANDLER-CASE} на \code{RESTART-CASE}. Форма
\code{RESTART-CASE} довольно похожа на \code{HANDLER-CASE} за исключением того, что имена
перезапусков, это просто имена, не обязательно имена типов условия. В общем, имя
перезапуска должно описывать действие, которое перезапуск совершает. В
\code{parse-log-file} вы можете вызвать перезапуск \code{skip-log-entry} так как он делает
именно "пропустить-журнальную-запись". Новая версия будет выглядеть так:

\begin{lstlisting}
(defun parse-log-file (file)
  (with-open-file (in file :direction :input)
    (loop for text = (read-line in nil nil) while text
       for entry = (restart-case (parse-log-entry text)
                     (skip-log-entry () nil))
       when entry collect it)))
\end{lstlisting}

Если вы вызовете эту версию \code{parse-log-file} на журнальном файле, содержащем
повреждённую запись, она не обработает ошибку напрямую; вы попадёте в отладчик. Однако
там, среди различных представленных перезапусков от отладчика будет один, называемый
\code{skip-log-entry}, который, если вызовете его, продолжит выполнение
\code{parse-log-file} дальше в прежнем режиме. Для избежания попадания в отладчик, вы
можете установить обработчик условия, который вызовет перезапуск \code{skip-log-entry}
автоматически.

Преимущество установки перезапуска вместо обработки ошибки напрямую в
\code{parse-log-file} в том, что это даёт возможность использовать \code{parse-log-file} в
большем количестве ситуаций. Код высшего уровня, который вызывает \code{parse-log-file},
не обязан вызывать перезапуск \code{skip-log-entry}. Он может выбрать обработку ошибки на
высшем уровне. Или, как я покажу в следующей секции, вы можете добавить перезапуск в
\code{parse-log-entry}, чтобы предоставить другую стратегию исправления и затем обработчик
условия может выбрать какую стратегию он хочет использовать.

Но перед этим вам надо увидеть как установить обработчик условия, который будет вызывать
\code{skip-log-entry} перезапуск. Вы можете установить обработчик где угодно в цепочке
вызовов ведущей к \code{parse-log-file}. Это может быть довольно высокий уровень в вашем
приложении, не обязательно в функции, непосредственно вызывающей
\code{parse-log-file}. Например, предположим, что главная точка входа в ваше приложение,
это функция \code{log-analyzer}, которая ищет стопку журналов и анализирует их функцией
\code{analyze-log}, которая в итоге приводит к вызову \code{parse-log-file}. Без
какой-либо обработки ошибок, это может выглядеть так:

\begin{lstlisting}
(defun log-analyzer ()
  (dolist (log (find-all-logs))
    (analyze-log log)))
\end{lstlisting}

Работа \code{analyze-log}~--- это вызвать прямо или непрямо \code{parse-log-file} и затем
сделать что-то с возвращённым списком журнальных записей. Сверхпростая версия может
выглядеть так:

\begin{lstlisting}
(defun analyze-log (log)
  (dolist (entry (parse-log-file log))
    (analyze-entry entry)))
\end{lstlisting}

где функция \code{analyze-entry} предположительно ответственна за извлечение заботящей вас
информации про каждую журнальную запись и припрятывание её куда-нибудь.

Таким образом, путь от функции высшего уровня \code{log-analyzer} к
\code{parse-log-entry}, которая собственно сигнализирует про ошибку, следующий:

%TODO: add picture
%{{ pcl:restart-call-stack.png  }}

Предполагая, что вы всегда хотите пропускать неправильно сформированные записи, вы можете
изменить эту функцию для установки обработчика условия, который вызывает перезапуск
\code{skip-log-entry} для вас. Однако вы не можете использовать \code{HANDLER-CASE} для
установки обработчика условия, потмоу что тогда стек будет опустошён до функции, где
\code{HANDLER-CASE} появляется. Вместо этого, вам надо использовать макрос нижнего уровня
\code{HANDLER-BIND}. Основная форма \code{HANDLER-BIND} следующая:

\begin{lstlisting}
(handler-bind (binding*) form*)
\end{lstlisting}

где каждая привязка (binding) представляет собой список из типа услоия и обрабатывающей
функции с одним аргументом. После провязок с обработчиками, тело \code{HANDLER-BIND} может
содержать произвольное число форм. В отличие от кода обработчика в \code{HANDLER-CASE},
код обработчика должен быть FIXME функцией-объектом и должен принимать единственный
аргумент. Более важным различием между \code{HANDLER-BIND} и \code{HANDLER-CASE} является
то, что функция обработки привязанная через \code{HANDLER-BIND} будет запущена без
опустошения стека~--- поток контроля будет всё ещё в вызове \code{parse-log-entry} если
эта функция вызвана. Вызов \code{INVOKE-RESTART} найдёт и вызовет последний связанный
перезапуск с данным именем. Таким образом вы можете добавить обработчик к
\code{log-analyzer} который будет вызывать \code{skip-log-entry} перезапуск, установленный
в \code{parse-log-file} таким образом:\footnote{Компилятор может возмутиться если параметр
    нигде не используется. Вы можете подавить это предупреждение, добавив объявление
    \code{(declare (ignore c}} как первое выражение в тело \code{LAMBDA}.))

\begin{lstlisting}
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error
                  #'(lambda (c)
                      (invoke-restart 'skip-log-entry))))
    (dolist (log (find-all-logs))
      (analyze-log log))))
\end{lstlisting}

В этом \code{HANDLER-BIND} обработчик является безымянной функцией, которая вызывает
перезапуск \code{skip-log-entry}. Вы также могли бы определить функцию с именем, которая
делала бы тоже самое и связать всё с ней. Фактически это обычная практика, когда
определение перезапуска является опрделением функции с тем же именем и получающую
единственный аргумент, условие, которая вызывает одноимённый перезапуск. Такие функции
называются функциями перезапуска. Можно определить функцию перезапуска
\code{skip-log-entry} так:

\begin{lstlisting}
(defun skip-log-entry (c)
  (invoke-restart 'skip-log-entry))
\end{lstlisting}

Затем вы могли бы изменить определение \code{log-analyzer} на такое:

\begin{lstlisting}
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error #'skip-log-entry))
    (dolist (log (find-all-logs))
      (analyze-log log))))
\end{lstlisting}

Как уже было сказано, функция перезапуска \code{skip-log-entry} полагает, что перезапуск
\code{skip-log-entry} уже был установлен. Если \code{malformed-log-entry-error}
просигнализирован кодом, вызванным из \code{log-analyzer} без уже установленного
\code{skip-log-entry}, вызов \code{INVOKE-RESTART} будет сигнализировать
\code{CONTROL-ERROR}, когда не сможет обнаружить перезапуск \code{skip-log-entry}. Если вы
хотите допустить возможность того, чтобы \code{malformed-log-entry-error} могло быть
просигнализировано из кода в котором перезапуск \code{skip-log-entry} не установлен, то вы
можете изменить функцию \code{skip-log-entry} таким образом:

\begin{lstlisting}
(defun skip-log-entry (c)
  (let ((restart (find-restart 'skip-log-entry)))
    (when restart (invoke-restart restart))))
\end{lstlisting}

\code{FIND-RESTART} ищет перезапуск с данным именем и возвращает объект, представляющий
перезапуск, если перезапуск найден или \code{NIL} если нет. Вы можете вызвать перезапуск
путём посылки перезапуск-объекта к \code{INVOKE-RESTART}. Таким образом, когда
\code{skip-log-entry} привязывается внутри \code{HANDLER-BIND}, она будет обрабатывать
условие путём вызова перезапуска \code{skip-log-entry}, если тот доступен или, в противном
случае, нормально завершится, давая другим обработчикам условия, привязанным выше по
стеку, шанс таки обработать условие.

\section{Предоставление множественных перезапусков}

Так как перезапуски должны быть прямо вызваны, чтобы был какой-то эффект, вы можете
определить несколько перезапусков, предоставляющих различную стратегию исправления. Как я
упоминал ранее, не все приложения для разбора журналов будут обязательно хотеть пропускать
неправильные записи. Некоторые приложения могут захотеть, чтобы \code{parse-log-file}
включала специальный тип объекта для представления неправильной записи в списке
\code{log-entry} объектов; другие приложения могут иметь несколько путей для
восстановления неправильной записи и могут хотеть иметь способ отправки исправленной
записи назад в \code{parse-log-entry}.

Чтобы позволить существовать более сложным протоколам исправления, перезапуски могут
получать произвольные аргументы, которые передаются в вызове \code{INVOKE-RESTART}. Вы
можете предоставить поддержку для обеих стратегий исправления, которые я упомянул, путём
добавления двух перезапусков к \code{parse-log-entry}, каждый из которых получает
единственный аргумент. Первый просто возвращает значение, которое получил, как значение
всего \code{parse-log-entry}, в то время как другой пытается разобрать свой аргумент на
месте оригинальной журнальной записи.

\begin{lstlisting}
(defun parse-log-entry (text)
  (if (well-formed-log-entry-p text)
    (make-instance 'log-entry ...)
    (restart-case (error 'malformed-log-entry-error :text text)
      (use-value (value) value)
      (reparse-entry (fixed-text) (parse-log-entry fixed-text)))))
\end{lstlisting}

Имя \code{USE-VALUE} является стандартным именем для такого типа перезапуска. Common Lisp
определяет функцию для \code{USE-VALUE} аналогично \code{skip-log-entry} функции, только
что вами определённой. Таким образом, если вы хотели изменить политику по отношению к
неправильным записям на ту, которая создана экземпляром \code{malformed-log-entry}, вы
могли бы сменить \code{log-analyzer} на такую функцию (предполагая существование
\code{malformed-log-entry} класса с инициирующим аргументом \code{:text}):

\begin{lstlisting}
(defun log-analyzer ()
  (handler-bind ((malformed-log-entry-error
                  #'(lambda (c)
                      (use-value
                       (make-instance 'malformed-log-entry :text (text c))))))
    (dolist (log (find-all-logs))
      (analyze-log log))))
\end{lstlisting}

Вы могли бы точно также поместить эти новые перезапуски в \code{parse-log-file} вместо
\code{parse-log-entry}. Хотя вы, вообще-то, хотите поместить перезапуски в код
по-возможности самого нижнего уровня. Не было бы, однако, правильным перемещать перезапуск
\code{skip-log-entry} в \code{parse-log-entry}, так как это может привести к возвращению
иногда \code{'NIL} от \code{parse-log-entry} в качестве результата нормального завершения,
а вы начинали всё с тем, чтобы таких вещей избежать. И это была бы одинаково плохая идея
убрать перезапуск \code{skip-log-entry} исходя из теории, что обработчик условия смог бы
достичь того же эффекта через вызов перезапуск \code{use-value} с \code{NIL} в качестве
аргумента; это потребовало бы от обработчика условия знания внутренней работы
\code{parse-log-file}. Таким образом \code{skip-log-entry}~--- правильно абстрагированная
часть API журнального разбора.

\section{Другие применения условий}

В то время, как условия в основном используются для обработки ошибок, они также могут быть
использованы для других целей~--- вы можете применить условия, обработчики условий и
перезапуски для конструирования различных протоколов между низко и высокоуровневым
кодом. Ключом для понимания возможностей условий является понимание того, что просто
сигнализация условия не влияет на поток контроля.

Примитивная сигнальная функция \code{SIGNAL} воплощает механизм поиска применимого
обработчика условия и вызывает его обрабатывающую функцию. Причина, почему обработчик
может отказаться обрабатывать условие и нормально завершиться, это потому что вызов
функции обработчика, это обычный вызов функции~--- когда обработчик завершается, контроль
передаётся обратно к \code{SIGNAL}, которая затем ищет другой, ранее привязанный
обработчик, который может обработать условие. Если \code{SIGNAL} исчерпает обработчики
условия до того, как условие будет обработано, она также завершается нормально.

Ранее использованная вами функция \code{ERROR} вызывает \code{SIGNAL}. Если ошибка
обрабатывается обработчиком условия, который передаёт управление через \code{HANDLER-CASE}
или через вызов перезапуска, тогда вызов \code{SIGNAL} никогда не завершится. Но если
\code{SIGNAL} завершается, \code{ERROR} вызывает отладчик путём вызова функции,
сохранённой в \code{*DEBUGGER-HOOK*}. Таким образом вызов \code{ERROR} никогда не сможет
завершиться нормально; условие должно быть обработано или обработчиком условия или в
отладчике.

Другая сигнализирующая условие функция \code{WARN}, представляет пример протокола ещё
одного типа, построенный на системе условий. Подобно \code{ERROR}, \code{WARN} вызывает
\code{SIGNAL} для сигнализации условия. Но, если \code{SIGNAL} завершается, \code{WARN} не
вызывает отладчик~--- она печатает условие в \code{*ERROR-OUTPUT*} и возвращает
\code{NIL}, позволяя своему вызывающему продолжать работу. \code{WARN} также устанавливает
перезапуск \code{MUFFLE-WARNING}, FIXME обёртку вызова \code{SIGNAL}, которая может быть
использована обработчиком условия, чтобы сделать возврат из \code{WARN} без печатания чего
либо. Функция \code{MUFFLE-WARNING} перезапуска, ищет и вызывает одноимённый перезапуск,
сигнализируя \code{CONTROL-ERROR}, если такого перезапуска нет. Конечно условие,
сигнализируемое \code{WARN}, также может быть обработано другим путём~--- обработчик
условия может "\textit{поспособствовать}", чтобы предупреждение об ошибке обрабатывалось,
как если бы ошибка действительно была.

Например в приложении для разбора журналов, если журнальная запись немного неправильна, но
всё же поддаётся разбору, вы могли бы указать \code{parse-log-entry} разобрать немного
повреждённую запись, но сигнализировать \code{WARN}, когда она будет делать это. Затем
большее приложение может выбрать либо позволить предупреждению быть напечатанным, либо
скрыть предупреждение, либо рассматривать предупреждение как ошибку, исправляя ситуацию
как это делалось при \code{malformed-log-entry-error}.

Третья сигнализирующая ошибки функция, \code{CERROR}, представляет ещё один протокол.
Подобно \code{ERROR}, \code{CERROR} сбросит вас в отладчик, если условие, которая она
сигнализирует, не будет обработано. Однако как и \code{WARN}, она устанавливает перезапуск
перед сигнализацией условия. Перезапуск, \code{CONTINUE}, приведёт к нормальному
завершению \code{CERROR}~--- если перезапуск был вызван обработчиком условия, он вообще
сохранит вас от попадания в отладчик. FIXME В противном случае, вы можете использовать
перезапуск, как только окажетесь в отладчике для продолжения вычислений сразу после вызова
\code{CERROR}. Функция \code{CONTINUE} находит и вызывает \code{CONTINUE} перезапуск, если
он доступен, и возвращает \code{NIL} в противном случае.

Вы также можете конструировать ваши собственные протоколы поверх \code{SIGNAL}~--- везде,
где низкоуровневый код нуждается в передаче информации назад по стеку вызовов в
высокоуровневый код, механизм условий является подходящим механизмом для использования. Но
для большинства целей один из стандартных протоколов ошибок или предупреждений должен
подойти.

Вы будете использовать систему условий в будущих практических главах, как в виде обычной
обработки ошибок, так и, в 25-й главе, для помощи в обработке мудрёного особого случая при
разборе ID3 файлов.  К сожалению, это судьба обработки ошибок, всегда идти мелким шрифтом
в программных текстах~--- надлежащая обработка ошибок или отсутствие таковой, является
часто наибольшим отличием иллюстративного кода и утяжелённого кода промышленного качества.
Хитрость написания последнего относится больше к принятию особого строгого образа мышления
о программном обеспечении, чем к деталями конструкции языка. Так что если вашей целью
является написание такого типа программ, то вы найдёте систему условий в Common Lisp
отличным инструментом для написания надёжного кода и прекрасно подходящей для стиля
последовательных улучшений (incremental development style).


%% START OF TABLE
Написание надёжных программ 

Для информации по написанию надёжных программ нет ничего лучше, чем начать с поиска книги
Гленфорда Меерса "Надёжность программного обеспечания" \textit{Software Reliability}
Glenford J. Meyers (John Wiley \& Sons, 1976). Написанное Bertrand Meyer про Design By
Contract также показывает полезный путь в размышлениях про правильность
программ. Например, смотрите главы 11 и 12 его \textit{Object-Oriented Software
  Construction} (Prentice Hall, 1997). Запомните, однако, что Bertrand Meyer является
изобретателем Eiffel, статически типизированного крепостнического и дисциплинарного языка
из школы Algol/Ada. Хотя у него есть много умных мыслей про объектную ориентированность и
программную надёжность, всё же существует довольно большой разрыв между его видением
программирования и путём Лиспа. Наконец, для прекрасного обзора большинства проблем,
окружающих построение отказоустойчивых систем, смотрите главу 3 из классической
\textit{Transaction Processing: Concepts and Techniques} (Morgan Kaufmann, 1993) от Jim
Gray и Andreas Reuter.

%% END OF TABLE

В следующей главе я дам быстрый обзор некоторых из 25 специальных операторов, которых у
вас пока не было шанса использовать, по крайней мере прямо.

%%% Local Variables: 
%%% mode: latex
%%% TeX-master: "pcl-ru"
%%% TeX-open-quote: "<<"
%%% TeX-close-quote: ">>"
%%% End: 
